meta:
  engine: 4.1.0
  name: dlp
  version: 0.1
  ref: &kb_ref "Helipad v0.1"
  author: daniel-luan
  url: &kb_url https://github.com/daniel-luan/helipad

presets:
  choc_v1:
    # Key and keycap measures
    kx: cx # spacing between key centers (X-axis)
    ky: cy # spacing between key centers (Y-axis)
    ks: 18 # horizontal space between columns (default: 19)
    kp: 17 # vertical padding between keys (deafult: 19)
    # ks: 18.5 # horizontal space between columns (default: 19)
    # kp: 17.5 # vertical padding between keys (deafult: 19)
    kcow: 13.8 # key cutout hole width (cherry, choc v2: 14, choc v1: 13.8)
    kcoh: 13.8 # key cutout hole height (cherry, choc v2: 14, choc v1: 13.8)
    keycw: 17.5 # keycap width (cherry: 18, choc: 17.5)
    keych: 16.5 # keycap height (cherry: 18, choc: 16.5)
    led_pos_x: 0 # Led X position relative to the switch center
    led_pos_y: 4.7 # Led Y position relative to the switch center
    led_rotation: 0 # Led rotation
    vertical_underglow_shift: -kp + 7.8  # How much to shift underglow leds tied to keys
    vertical_diode_shift: 1.5 # How much to shift to avoid overlap
    horizontal_diode_shift: -0.5 kcow - 0.85
    diode_rotation: -180 # Diode rotation
    switch_rotation: 180 # Hotswap south, led north


units:
  # The following statements will make the content of the preset
  # available in the units context
  $extends: presets.choc_v1

  # Physical measures
  screw_radius: 1.1 # M2 screws
  screw_diameter: screw_radius * 2
  # screw_head_radius: 2.05
  # screw_head_diameter: screw_head_radius * 2
  # spacer_radius: 2.15 # M2 standoffs
  # spacer_diameter: spacer_radius * 2
  fillet_radius: 0.5
  # pwr_trace_width: 0.25
  # gnd_trace_width: 0.25
  # signal_trace_width: 0.15
  # via_size: 0.56 # JLCPCB min 0.56 | KiCad default 0.8
  # via_drill: 0.3 # JLCPCB min 0.3 | KiCad default 0.4

points:

  zones:
    matrix:
      key:
        padding: kp
        spread: ks
        tags: 
          - key
          - matrix_key
      columns:
        outer:
          key:
            column_net: C0
        pinky:
          key:
            column_net: C1
        ring:
          key:
            column_net: C2
        middle:
          key:
            column_net: C3
        index:
          key:
            column_net: C4
        inner:
          key:
            column_net: C5
        extraInner:
          key:
            skip: true
            column_net: C6
          rows:
            bottom.skip: false
            mod.skip: false
      rows:
        mod:
          row_net: R4
        bottom:
          row_net: R3
        home:
          row_net: R2
        top:
          row_net: R1
        num:
          row_net: R0

outlines:
  raw:
    - what: rectangle
      fillet: fillet_radius
      size: [7*ks+3, 5*kp]
      where:
        shift: [1, 0]
        ref: matrix_middle_home
  keycap_outlines:
    - what: rectangle
      fillet: fillet_radius
      where: [key]
      size: [keycw, keych]
  keyswitch_cutouts:
    - what: rectangle
      fillet: fillet_radius
      where: [key]
      size: [kcow, kcoh]
  preview:
    - what: outline
      name: raw
    - what: outline
      name: keycap_outlines
      operation: stack
    - what: outline
      name: keyswitch_cutouts
      operation: stack

pcbs:
  helipad:
    template: kicad8
    outlines:
      main:
        outline: raw
    footprints:
      choc:
        what: ceoloide/switch_choc_v1_v2
        where: true
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          include_keycap: true
          choc_v2_support: false
          reversible: true
          hotswap: true
          include_plated_holes: true
          include_centerhole_net: true
          keycap_width: keycw
          keycap_height: keych
        adjust:
          rotate: switch_rotation

      diode:
        what: ceoloide/diode_tht_sod123
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          include_tht: true
          reversible: true
        adjust:
          shift: [0, 5]
          rotate: 180

      promicro:
        what: ceoloide/mcu_nice_nano
        where:
          ref: matrix_extraInner_bottom
          # shift: [18.5, -10.5]
          shift: [1.75, 42]
          # rotate: -90
        params:
          # P0: CS
          # P1: CS
          P10: CS
          P21: C0
          P20: C1
          P19: C2
          P18: C3
          P15: C4
          P14: C5
          P16: C6
          P2: SDA
          P3: SCL
          P4: R0
          P5: R1
          P6: R2
          P7: R3
          P8: R4
          reversible: true
          include_traces: true
          show_silk_labels: true
          show_via_labels: true
          show_instructions: false
          use_rectangular_jumpers: true
          reverse_mount: false
          # side: B

      nice_view:
        what: ceoloide/display_nice_view
        where: matrix_extraInner_bottom
        params:
          MOSI: SDA
          SCK: SCL
          reversible: true
          include_labels: false
          invert_jumpers_position: true
        adjust:
          shift: [1.75, 40]
      
      on_off_switch:
        what: ceoloide/power_switch_smd_side
        where: matrix_extraInner_bottom
        params:
          from: BAT_P
          to: RAW
          reversible: true
        adjust:
          shift: [0.5 ks + 0.7, 15]
      
      reset_switch:
        what: ceoloide/reset_switch_tht_top
        where: matrix_extraInner_bottom
        params:
          from: GND
          to: RST
          reversible: true
        adjust:
          shift: [0, 18]
      
      battery_connector:  
        what: ceoloide/battery_connector_jst_ph_2
        where: matrix_extraInner_bottom
        params:
          BAT_P: BAT_P
          BAT_N: GND
          reversible: true
          # include_courtyard: false
        adjust:
          shift: [-5, 12]
          rotate: 90
      mounting_hole:
        what: ceoloide/mounting_hole_plated
        where: [matrix_outer_top, matrix_outer_mod, matrix_index_top, matrix_inner_mod, matrix_ring_bottom]
        params:
          drill: screw_diameter
        adjust:
          shift: [0.5ks, 0.5kp]